# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: my_service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'my_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10my_service.proto\"\xf6\x01\n\x0bJsonRequest\x12\x11\n\tSpaceName\x18\x01 \x01(\t\x12\x10\n\x08ParentId\x18\x02 \x01(\t\x12\x0c\n\x04Type\x18\x03 \x01(\t\x12\x13\n\x0bXCoordinate\x18\x04 \x01(\x02\x12\x13\n\x0bYCoordinate\x18\x05 \x01(\x02\x12\x13\n\x0bZCoordinate\x18\x06 \x01(\x02\x12\x10\n\x08Rotation\x18\x07 \x01(\x02\x12\x10\n\x08RackSide\x18\x08 \x01(\t\x12\n\n\x02RU\x18\t \x01(\x05\x12\x10\n\x08Location\x18\n \x01(\x05\x12\x0f\n\x07UHeight\x18\x0b \x01(\x05\x12\x0f\n\x07XOffset\x18\x0c \x01(\x02\x12\x11\n\tXPosition\x18\r \x01(\x02\" \n\x0cJsonResponse\x12\x10\n\x08response\x18\x01 \x01(\t2;\n\tMyService\x12.\n\x0fGetJsonResponse\x12\x0c.JsonRequest\x1a\r.JsonResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'my_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JSONREQUEST']._serialized_start=21
  _globals['_JSONREQUEST']._serialized_end=267
  _globals['_JSONRESPONSE']._serialized_start=269
  _globals['_JSONRESPONSE']._serialized_end=301
  _globals['_MYSERVICE']._serialized_start=303
  _globals['_MYSERVICE']._serialized_end=362
# @@protoc_insertion_point(module_scope)
